name: mova
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  widget_circular_animator: ^1.0.0
  google_fonts: 3.0.1
  lottie: 1.3.0
  auto_size_text: ^3.0.0
  line_icons: ^2.0.1
  flutter_svg: 1.0.3
  image_picker: 0.8.5+3
  pin_code_fields: 7.4.0
  awesome_dialog: 2.2.1
  flutter_countdown_timer: 4.1.0
  blur_bottom_bar: 1.0.3
  modal_bottom_sheet: 2.0.1
  readmore: 2.2.0
  flutter_rating_bar: 4.0.1
  chewie: 1.3.4
  video_player: 2.4.5
  flutter_switch: 0.3.2
  get_storage: 2.0.3
  firebase_core: ^1.22.0
  google_sign_in: 5.4.0
  firebase_auth: ^3.9.0
  cloud_firestore: ^3.4.8
  firebase_storage: ^10.3.8
  dio: 4.0.6
  form_validator: 1.0.2
  jwt_decoder: 2.0.1
  timeago: 3.3.0
  url_launcher: 6.1.5
  webview_flutter: 3.0.4
  flutter_webview_plugin: 0.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - asset/lottie/
    - asset/image/
    - asset/svg/
    - asset/video/
  uses-material-design: true

