part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const INTRODUCTION = _Paths.INTRODUCTION;
  static const CUSTOM_AUTH = _Paths.CUSTOM_AUTH;
  static const LOGIN = _Paths.LOGIN;
  static const REGISTER = _Paths.REGISTER;
  static const INTEREST = _Paths.INTEREST;
  static const FILL_PROFILE = _Paths.FILL_PROFILE;
  static const NEW_PIN = _Paths.NEW_PIN;
  static const FORGET_PASSWORD_1 = _Paths.FORGET_PASSWORD_1;
  static const FORGET_PASSWORD_2_SMS = _Paths.FORGET_PASSWORD_2_SMS;
  static const FORGET_PASSWORD_2_EMAIL = _Paths.FORGET_PASSWORD_2_EMAIL;
  static const FORGET_PASSWORD_3_SMS = _Paths.FORGET_PASSWORD_3_SMS;
  static const CREATE_NEW_PASSWORD = _Paths.CREATE_NEW_PASSWORD;
  static const NAVBAR = _Paths.NAVBAR;
  static const EXPLORE = _Paths.EXPLORE;
  static const MY_LIST = _Paths.MY_LIST;
  static const DOWNLOAD = _Paths.DOWNLOAD;
  static const PROFILE = _Paths.PROFILE;
  static const TOP_10 = _Paths.TOP_10;
  static const NEW_RELEASE = _Paths.NEW_RELEASE;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const SEARCH = _Paths.SEARCH;
  static const SERIES_DETAIL = _Paths.SERIES_DETAIL;
  static const MOVIE_DETAIL = _Paths.MOVIE_DETAIL;
  static const COMMENT = _Paths.COMMENT;
  static const VIDEO_PLAY = _Paths.VIDEO_PLAY;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const NOTIFICATION_SETTING = _Paths.NOTIFICATION_SETTING;
  static const DOWNLOAD_SETTING = _Paths.DOWNLOAD_SETTING;
  static const SECURITY = _Paths.SECURITY;
  static const SUBSCRIBE = _Paths.SUBSCRIBE;
  static const INTERSECTION = _Paths.INTERSECTION;
  static const MOVIE_COMMENT = _Paths.MOVIE_COMMENT;
  static const SERIES_COMMENT = _Paths.SERIES_COMMENT;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const INTRODUCTION = '/introduction';
  static const CUSTOM_AUTH = '/custom-auth';
  static const LOGIN = '/login';
  static const REGISTER = '/register';
  static const INTEREST = '/interest';
  static const FILL_PROFILE = '/fill-profile';
  static const NEW_PIN = '/new-pin';
  static const FORGET_PASSWORD_1 = '/forget-password-1';
  static const FORGET_PASSWORD_2_SMS = '/forget-password-2-sms';
  static const FORGET_PASSWORD_2_EMAIL = '/forget-password-2-email';
  static const FORGET_PASSWORD_3_SMS = '/forget-password-3-sms';
  static const CREATE_NEW_PASSWORD = '/create-new-password';
  static const NAVBAR = '/navbar';
  static const EXPLORE = '/explore';
  static const MY_LIST = '/my-list';
  static const DOWNLOAD = '/download';
  static const PROFILE = '/profile';
  static const TOP_10 = '/top-10';
  static const NEW_RELEASE = '/new-release';
  static const NOTIFICATION = '/notification';
  static const SEARCH = '/search';
  static const SERIES_DETAIL = '/series-detail';
  static const MOVIE_DETAIL = '/movie-detail';
  static const COMMENT = '/comment';
  static const VIDEO_PLAY = '/video-play';
  static const EDIT_PROFILE = '/edit-profile';
  static const NOTIFICATION_SETTING = '/notification-setting';
  static const DOWNLOAD_SETTING = '/download-setting';
  static const SECURITY = '/security';
  static const SUBSCRIBE = '/subscribe';
  static const INTERSECTION = '/intersection';
  static const MOVIE_COMMENT = '/movie-comment';
  static const SERIES_COMMENT = '/series-comment';
  static const SUBSCRIPTION = '/subscription';
}
